###
GET http://localhost:3000/cats
Content-Type: application/json

###
GET http://localhost:3000/cats/123
Content-Type: application/json

###
POST http://localhost:3000/cats
Content-Type: application/json

{
   "name": "Cat",
   "age": 7,
   "breed": "simple"
}

###
PUT http://localhost:3000/cats/1
Content-Type: application/json

###
DELETE http://localhost:3000/cats/1
Content-Type: application/json
